### ISSUE TITLE
询问代码使用事宜

### ISSUE THREAD

**Issue by Lahee-Ni** [SuperTyrael/LSGO_GAs#1]
您好，我是来自西安电子科技大学2018级软件工程专业本科生，毕业设计题目也是LSGO相关问题，之前苦苦寻找DECC-G等经典对照算法的代码，请问可否在毕业设计中使用您仓库的代码，我会在毕业论文中标注出处，如果可以，不胜感激！另外请教一下仓库中的代码是您本人亲自手写还是其他地方的搬运，若是后者，能否请教一下如何查找经典算法的源码？

**Comment by SuperTyrael** [comment]
这也是我的毕设，考虑到查重的等因素暂时不允许您使用。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月23日(周六) 上午6:49
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [SuperTyrael/LSGO_GAs] 询问代码使用事宜 (Issue #1)




 
您好，我是来自西安电子科技大学2018级软件工程专业本科生，毕业设计题目也是LSGO相关问题，之前苦苦寻找DECC-G等经典对照算法的代码，请问可否在毕业设计中使用您仓库的代码，我会在毕业论文中标注出处，如果可以，不胜感激！另外请教一下仓库中的代码是您本人亲自手写还是其他地方的搬运，若是后者，能否请教一下如何查找经典算法的源码？

**Comment by Lahee-Ni** [comment]
> 

收到，依然感谢您的分享！我会寻找其他对照算法。
